import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import type { Id } from "./_generated/dataModel";
import {
  hashSessionToken,
  requireUser,
  sessionByToken,
  SESSION_ABSOLUTE_TTL_MS,
  SESSION_SLIDING_TTL_MS,
  userBySessionToken,
} from "./helpers";
import {
  encryptedXTokenFields,
  encryptedXTokenPatch,
  readStoredXTokens,
} from "./tokenSecurity";
import { verifyProvisioningSecret } from "../shared/authProvisioning";

const SESSION_TTL_MS = SESSION_SLIDING_TTL_MS;
const TOKEN_ACCESS_SECRET_ENV = "CONVEX_SERVER_TOKEN_ACCESS_SECRET";
const AUTH_PROVISION_SECRET_ENV = "CONVEX_AUTH_PROVISION_SECRET";
const X_PROVIDER = "x";

function requireServerTokenAccess(secret: string) {
  const expected = process.env[TOKEN_ACCESS_SECRET_ENV]?.trim();
  if (!expected || secret !== expected) {
    throw new Error("Unauthorized");
  }
}

function requireAuthProvisioningSecret(secret: string | undefined, isDemo: boolean) {
  const decision = verifyProvisioningSecret({
    expected: process.env[AUTH_PROVISION_SECRET_ENV],
    provided: secret,
    requireWhenMissing: !isDemo,
  });
  if (!decision.ok) throw new Error("Unauthorized");
}

/**
 * Upsert a user after X OAuth (or demo login) and open a session.
 * Called server-side only; the session token is generated by the Next.js
 * auth route and stored in an httpOnly cookie.
 */
export const upsertAndCreateSession = mutation({
  args: {
    provisioningSecret: v.optional(v.string()),
    xUserId: v.string(),
    username: v.string(),
    displayName: v.string(),
    avatar: v.optional(v.string()),
    isDemo: v.boolean(),
    betaAccessExpiresAt: v.optional(v.number()),
    sessionToken: v.string(),
    xAuth: v.optional(
      v.object({
        accessToken: v.string(),
        refreshToken: v.optional(v.string()),
        expiresAt: v.number(),
        scope: v.string(),
      })
    ),
  },
  handler: async (ctx, args) => {
    requireAuthProvisioningSecret(args.provisioningSecret, args.isDemo);
    const now = Date.now();
    const identity = await ctx.db
      .query("accountIdentities")
      .withIndex("by_provider_and_provider_user_id", (q) =>
        q.eq("provider", X_PROVIDER).eq("providerUserId", args.xUserId)
      )
      .first();
    const identityUser = identity ? await ctx.db.get(identity.userId) : null;
    const existing =
      identityUser ??
      (await ctx.db
        .query("users")
        .withIndex("by_x_user_id", (q) => q.eq("xUserId", args.xUserId))
        .first());

    let userId: Id<"users">;
    if (existing) {
      userId = existing._id;
      await ctx.db.patch(userId, {
        username: args.username,
        displayName: args.displayName,
        avatar: args.avatar,
        betaAccessExpiresAt: args.betaAccessExpiresAt,
      });
    } else {
      userId = await ctx.db.insert("users", {
        xUserId: args.xUserId,
        username: args.username,
        displayName: args.displayName,
        avatar: args.avatar,
        plan: "free",
        isDemo: args.isDemo,
        betaAccessExpiresAt: args.betaAccessExpiresAt,
        createdAt: now,
      });
    }

    if (identity) {
      await ctx.db.patch(identity._id, {
        userId,
        lastLoginAt: now,
      });
    } else {
      await ctx.db.insert("accountIdentities", {
        provider: X_PROVIDER,
        providerUserId: args.xUserId,
        userId,
        createdAt: now,
        lastLoginAt: now,
      });
    }

    if (args.xAuth) {
      const tokenRow = await ctx.db
        .query("xTokens")
        .withIndex("by_user", (q) => q.eq("userId", userId))
        .unique();
      if (tokenRow) {
        await ctx.db.patch(tokenRow._id, {
          ...(await encryptedXTokenPatch({
            accessToken: args.xAuth.accessToken,
            refreshToken: args.xAuth.refreshToken,
            existingRefreshToken: tokenRow.refreshToken,
            existingEncryptedRefreshToken: tokenRow.encryptedRefreshToken,
          })),
          expiresAt: args.xAuth.expiresAt,
          scope: args.xAuth.scope,
        });
      } else {
        await ctx.db.insert("xTokens", {
          userId,
          ...(await encryptedXTokenFields({
            accessToken: args.xAuth.accessToken,
            refreshToken: args.xAuth.refreshToken,
          })),
          expiresAt: args.xAuth.expiresAt,
          scope: args.xAuth.scope,
        });
      }
    }

    await ctx.db.insert("sessions", {
      userId,
      tokenHash: await hashSessionToken(args.sessionToken),
      createdAt: now,
      lastSeenAt: now,
      expiresAt: now + SESSION_TTL_MS,
      absoluteExpiresAt: now + SESSION_ABSOLUTE_TTL_MS,
    });

    return userId;
  },
});

export const me = query({
  args: { sessionToken: v.string() },
  handler: async (ctx, { sessionToken }) => {
    const user = await userBySessionToken(ctx, sessionToken);
    if (!user) return null;
    const xToken = await ctx.db
      .query("xTokens")
      .withIndex("by_user", (q) => q.eq("userId", user._id))
      .unique();
    return {
      _id: user._id,
      username: user.username,
      displayName: user.displayName,
      avatar: user.avatar,
      plan: user.plan,
      betaAccessExpiresAt: user.betaAccessExpiresAt,
      defaultModel: user.defaultModel,
      goal: user.goal,
      onboardingCompletedAt: user.onboardingCompletedAt,
      setupDismissedAt: user.setupDismissedAt,
      isDemo: user.isDemo,
      createdAt: user.createdAt,
      xConnected: xToken !== null && xToken.expiresAt > Date.now(),
    };
  },
});

/** Save the primary goal chosen in onboarding. */
export const setGoal = mutation({
  args: {
    sessionToken: v.string(),
    goal: v.union(
      v.literal("audience"),
      v.literal("leads"),
      v.literal("authority")
    ),
  },
  handler: async (ctx, { sessionToken, goal }) => {
    const user = await requireUser(ctx, sessionToken);
    await ctx.db.patch(user._id, { goal });
  },
});

/** Mark onboarding finished (or skipped) so auth stops routing to the wizard. */
export const completeOnboarding = mutation({
  args: { sessionToken: v.string() },
  handler: async (ctx, { sessionToken }) => {
    const user = await requireUser(ctx, sessionToken);
    await ctx.db.patch(user._id, { onboardingCompletedAt: Date.now() });
  },
});

/** Hide the dashboard "finish setting up" card. */
export const dismissSetupChecklist = mutation({
  args: { sessionToken: v.string() },
  handler: async (ctx, { sessionToken }) => {
    const user = await requireUser(ctx, sessionToken);
    await ctx.db.patch(user._id, { setupDismissedAt: Date.now() });
  },
});

/** Set the user's preferred Claude model for reply generation. */
export const setDefaultModel = mutation({
  args: { sessionToken: v.string(), model: v.string() },
  handler: async (ctx, { sessionToken, model }) => {
    const user = await requireUser(ctx, sessionToken);
    await ctx.db.patch(user._id, { defaultModel: model });
  },
});

/**
 * X identity metadata for the current session. This is safe for the browser:
 * it never returns stored X OAuth token material.
 */
export const xAuthForSession = query({
  args: { sessionToken: v.string() },
  handler: async (ctx, { sessionToken }) => {
    const user = await userBySessionToken(ctx, sessionToken);
    if (!user) return null;
    const tokenRow = await ctx.db
      .query("xTokens")
      .withIndex("by_user", (q) => q.eq("userId", user._id))
      .unique();
    return {
      xUserId: user.xUserId,
      isDemo: user.isDemo,
      expiresAt: tokenRow?.expiresAt ?? 0,
      scope: tokenRow?.scope ?? "",
    };
  },
});

/**
 * X identity + decrypted access token for server-only Next paths. Convex public
 * functions are Internet-callable, so a separate server secret is required in
 * addition to the user's session token.
 */
export const xAuthForServerSession = query({
  args: { sessionToken: v.string(), serverSecret: v.string() },
  handler: async (ctx, { sessionToken, serverSecret }) => {
    requireServerTokenAccess(serverSecret);
    const user = await userBySessionToken(ctx, sessionToken);
    if (!user) return null;
    const tokenRow = await ctx.db
      .query("xTokens")
      .withIndex("by_user", (q) => q.eq("userId", user._id))
      .unique();
    const tokens = await readStoredXTokens(tokenRow);
    return {
      xUserId: user.xUserId,
      isDemo: user.isDemo,
      accessToken:
        tokenRow && tokenRow.expiresAt > Date.now() ? tokens.accessToken : null,
      refreshToken: tokens.refreshToken,
      expiresAt: tokenRow?.expiresAt ?? 0,
      scope: tokenRow?.scope ?? "",
    };
  },
});

/** Update stored X OAuth tokens after a refresh from a server action. */
export const persistXTokensFromSession = mutation({
  args: {
    sessionToken: v.string(),
    accessToken: v.string(),
    refreshToken: v.optional(v.string()),
    expiresAt: v.number(),
    scope: v.string(),
  },
  handler: async (ctx, args) => {
    const user = await requireUser(ctx, args.sessionToken);
    const tokenRow = await ctx.db
      .query("xTokens")
      .withIndex("by_user", (q) => q.eq("userId", user._id))
      .unique();
    if (!tokenRow) return;

    await ctx.db.patch(tokenRow._id, {
      ...(await encryptedXTokenPatch({
        accessToken: args.accessToken,
        refreshToken: args.refreshToken,
        existingRefreshToken: tokenRow.refreshToken,
        existingEncryptedRefreshToken: tokenRow.encryptedRefreshToken,
      })),
      expiresAt: args.expiresAt,
      scope: args.scope || tokenRow.scope,
    });
  },
});

export const logout = mutation({
  args: { sessionToken: v.string() },
  handler: async (ctx, { sessionToken }) => {
    const session = await sessionByToken(ctx, sessionToken);
    if (session) await ctx.db.delete(session._id);
  },
});
