import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import { userBySessionToken } from "./helpers";

const SESSION_TTL_MS = 1000 * 60 * 60 * 24 * 30; // 30 days

/**
 * Upsert a user after X OAuth (or demo login) and open a session.
 * Called server-side only; the session token is generated by the Next.js
 * auth route and stored in an httpOnly cookie.
 */
export const upsertAndCreateSession = mutation({
  args: {
    xUserId: v.string(),
    username: v.string(),
    displayName: v.string(),
    avatar: v.optional(v.string()),
    isDemo: v.boolean(),
    sessionToken: v.string(),
    xAuth: v.optional(
      v.object({
        accessToken: v.string(),
        refreshToken: v.optional(v.string()),
        expiresAt: v.number(),
        scope: v.string(),
      })
    ),
  },
  handler: async (ctx, args) => {
    const now = Date.now();
    const existing = await ctx.db
      .query("users")
      .withIndex("by_x_user_id", (q) => q.eq("xUserId", args.xUserId))
      .unique();

    let userId;
    if (existing) {
      userId = existing._id;
      await ctx.db.patch(userId, {
        username: args.username,
        displayName: args.displayName,
        avatar: args.avatar,
      });
    } else {
      userId = await ctx.db.insert("users", {
        xUserId: args.xUserId,
        username: args.username,
        displayName: args.displayName,
        avatar: args.avatar,
        plan: "free",
        isDemo: args.isDemo,
        createdAt: now,
      });
    }

    if (args.xAuth) {
      const tokenRow = await ctx.db
        .query("xTokens")
        .withIndex("by_user", (q) => q.eq("userId", userId))
        .unique();
      if (tokenRow) {
        await ctx.db.patch(tokenRow._id, { ...args.xAuth });
      } else {
        await ctx.db.insert("xTokens", { userId, ...args.xAuth });
      }
    }

    await ctx.db.insert("sessions", {
      userId,
      token: args.sessionToken,
      createdAt: now,
      expiresAt: now + SESSION_TTL_MS,
    });

    return userId;
  },
});

export const me = query({
  args: { sessionToken: v.string() },
  handler: async (ctx, { sessionToken }) => {
    const user = await userBySessionToken(ctx, sessionToken);
    if (!user) return null;
    const xToken = await ctx.db
      .query("xTokens")
      .withIndex("by_user", (q) => q.eq("userId", user._id))
      .unique();
    return {
      _id: user._id,
      username: user.username,
      displayName: user.displayName,
      avatar: user.avatar,
      plan: user.plan,
      isDemo: user.isDemo,
      createdAt: user.createdAt,
      xConnected: xToken !== null && xToken.expiresAt > Date.now(),
    };
  },
});

/**
 * X identity + access token for the current session. Only callable with a
 * valid session token; used by server actions that talk to the X API.
 */
export const xAuthForSession = query({
  args: { sessionToken: v.string() },
  handler: async (ctx, { sessionToken }) => {
    const user = await userBySessionToken(ctx, sessionToken);
    if (!user) return null;
    const tokenRow = await ctx.db
      .query("xTokens")
      .withIndex("by_user", (q) => q.eq("userId", user._id))
      .unique();
    return {
      xUserId: user.xUserId,
      isDemo: user.isDemo,
      accessToken:
        tokenRow && tokenRow.expiresAt > Date.now() ? tokenRow.accessToken : null,
    };
  },
});

export const logout = mutation({
  args: { sessionToken: v.string() },
  handler: async (ctx, { sessionToken }) => {
    const session = await ctx.db
      .query("sessions")
      .withIndex("by_token", (q) => q.eq("token", sessionToken))
      .unique();
    if (session) await ctx.db.delete(session._id);
  },
});
