/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/dark-chrome.source.ts
 * Command: astryx theme build src/theme/dark-chrome.source.ts --out src/theme/dark-chrome.css
 * Generated: 2026-07-09T16:24:23.095Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const darkChromeTheme: DefinedTheme;
