/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/dark-chrome.source.ts
 * Command: astryx theme build src/theme/dark-chrome.source.ts --out src/theme/dark-chrome.css
 * Generated: 2026-07-10T14:15:24.202Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const darkChromeTheme: DefinedTheme;
